# Generated by Django 3.0.7 on 2020-08-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('school_name', models.CharField(max_length=20)),
                ('school_address', models.CharField(max_length=20)),
                ('academic_level', models.CharField(choices=[('PRI', 'Primary'), ('SEC', 'Secondary'), ('GRAD', 'Graduate')], default='PRI', max_length=4)),
                ('completion_year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020)),
                ('reason', models.TextField(help_text='Tell us why we should sponsor you')),
                ('birth_certificate', models.FileField(upload_to='docs/')),
                ('national_id', models.FileField(upload_to='docs/')),
                ('recommendation_letter', models.FileField(upload_to='docs/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_sponsored', models.BooleanField(default=False)),
            ],
        ),
    ]
